# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- powershell: |
    $FeedName = 'PSGallery'
    Install-PackageProvider Nuget -Scope CurrentUser -Force
    Install-module PSScriptAnalyzer -force -Scope CurrentUser -Repository $FeedName
    Install-module PSPesterTest -force -Scope CurrentUser -Repository $FeedName
  displayName: 'Install required PowerShell modules'

- task: richardfennellBM.BM-VSTS-PesterRunner-Task.Pester-Task.Pester@8
  displayName: 'Pester Test Runner - Hub Network Template'
  inputs:
    scriptFolder: '@{Path=''$(System.DefaultWorkingDirectory)\tests\ARMTemplate\Test.ARMTemplate.ps1''; Parameters=@{TemplatePath =''$(System.DefaultWorkingDirectory)\templates\\hub\\hub.network.azuredeploy.json''; parameters =$(hubParameters); variables = $(hubVariables); resources = $(hubResources)}}'
    resultsFile: '$(System.DefaultWorkingDirectory)\TEST-Hub-Network.xml'

- task: richardfennellBM.BM-VSTS-PesterRunner-Task.Pester-Task.Pester@8
  displayName: 'Pester Test Runner - Spoke Network Template'
  inputs:
    scriptFolder: '@{Path=''$(System.DefaultWorkingDirectory)\tests\ARMTemplate\Test.ARMTemplate.ps1''; Parameters=@{TemplatePath =''$(System.DefaultWorkingDirectory)\templates\\spoke\\spoke.network.azuredeploy.json''; parameters =$(SpokeParameters); variables = $(SpokeVariables); resources = $(SpokeResources)}}'
    resultsFile: '$(System.DefaultWorkingDirectory)\TEST-Spoke-Network.xml'

- task: richardfennellBM.BM-VSTS-PesterRunner-Task.Pester-Task.Pester@8
  displayName: 'Pester Test Runner - VNet Peering Template'
  inputs:
    scriptFolder: '@{Path=''$(System.DefaultWorkingDirectory)\tests\ARMTemplate\Test.ARMTemplate.ps1''; Parameters=@{TemplatePath =''$(System.DefaultWorkingDirectory)\templates\\vnetPeering\\vnet.peering.azuredeploy.json''; parameters =$(peeringParameters); resources = $(peeringResources)}}'
    resultsFile: '$(System.DefaultWorkingDirectory)\TEST-Network-Peering.xml'

- task: richardfennellBM.BM-VSTS-PesterRunner-Task.Pester-Task.Pester@8
  displayName: 'Pester Test Runner - Private DNS Zone Template'
  inputs:
    scriptFolder: '@{Path=''$(System.DefaultWorkingDirectory)\tests\ARMTemplate\Test.ARMTemplate.ps1''; Parameters=@{TemplatePath =''$(System.DefaultWorkingDirectory)\templates\\private-dns-zone\\private.dns.zone.azuredeploy.json''; parameters =$(dnsZoneParameters); resources = $(dnsZoneResources)}}'
    resultsFile: '$(System.DefaultWorkingDirectory)\TEST-Private-DNS-Zone.xml'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  inputs:
    testResultsFormat: NUnit
